In [1]:
import numpy as np  # linear algebra
import pandas as pd  # data processing, CSV file I/O (e.g. pd.read_csv)


In [1]:

# sample = pd.read_csv('c:/data/amazon/sample_submission.csv')
# print(sample.shape)
# sample.head()

df = pd.read_csv('c:/data/amazon/train.csv')
print(df.head())
print(df.shape)

  image_name                                       tags
0    train_0                               haze primary
1    train_1            agriculture clear primary water
2    train_2                              clear primary
3    train_3                              clear primary
4    train_4  agriculture clear habitation primary road
(40479, 2)


In [2]:
# Tag counts
# First, let's count all of the tags.

all_tags = [item for sublist in
            list(df['tags']
                 .apply(lambda row: row.split(" "))
                 .values) for item in sublist]
print('total of {} non-unique tags in all training images'
      .format(len(all_tags)))
print('average number of labels per image {}'
      .format(1.0 * len(all_tags) / df.shape[0]))

# Now, lets do the actual counting. We're going to use pandas dataframe
# groupby method for that. In total, as we found in the description above,
# there are 17 distinct tags.

tags_counted_and_sorted = pd.DataFrame({'tag': all_tags}).groupby('tag').size().reset_index().sort_values(0, ascending=False)
print(tags_counted_and_sorted)


total of 116484 non-unique tags in all training images
average number of labels per image 2.8776402579115095
                  tag      0
12            primary  37840
5               clear  28203
0         agriculture  12338
13               road   8076
16              water   7262
11      partly_cloudy   7251
8         cultivation   4547
9          habitation   3662
10               haze   2695
6              cloudy   2330
2         bare_ground    859
14  selective_logging    340
1      artisinal_mine    339
3            blooming    332
15         slash_burn    209
4           blow_down    101
7   conventional_mine    100


In [6]:
df['tags']

0                                 haze primary
1              agriculture clear primary water
2                                clear primary
3                                clear primary
4    agriculture clear habitation primary road
Name: tags, dtype: object

In [10]:
# Build list with unique labels
label_list = []
for tag_str in df.tags.values:
    labels = tag_str.split(' ')
    for label in labels:
        if label not in label_list:
            label_list.append(label)

In [11]:
label_list

['haze',
 'primary',
 'agriculture',
 'clear',
 'water',
 'habitation',
 'road',
 'cultivation',
 'slash_burn',
 'cloudy',
 'partly_cloudy',
 'conventional_mine',
 'bare_ground',
 'artisinal_mine',
 'blooming',
 'selective_logging',
 'blow_down']

In [13]:
# Add onehot features for every label
for label in label_list:
    df[label] = df['tags'].apply(lambda x: 1 if label in x.split(' ') else 0)
# Display head
df.head()

image_name                                       tags  haze  primary  \
0    train_0                               haze primary     1        1   
1    train_1            agriculture clear primary water     0        1   
2    train_2                              clear primary     0        1   
3    train_3                              clear primary     0        1   
4    train_4  agriculture clear habitation primary road     0        1   

   agriculture  clear  water  habitation  road  cultivation  slash_burn  \
0            0      0      0           0     0            0           0   
1            1      1      1           0     0            0           0   
2            0      1      0           0     0            0           0   
3            0      1      0           0     0            0           0   
4            1      1      0           1     1            0           0   

   cloudy  partly_cloudy  conventional_mine  bare_ground  artisinal_mine  \
0       0              0                  0            0               0   
1       0              0                  0            0               0   
2       0              0                  0            0               0   
3       0              0                  0            0               0   
4       0              0                  0            0               0   

   blooming  selective_logging  blow_down  
0         0                  0          0  
1         0                  0          0  
2         0                  0          0  
3         0                  0          0  
4         0                  0          0

In [26]:
y = np.array(df.ix[:,2:])
#y = np.array(df[label])
y

array([[1, 1, 0, ..., 0, 0, 0],
       [0, 1, 1, ..., 0, 0, 0],
       [0, 1, 0, ..., 0, 0, 0],
       ..., 
       [0, 1, 1, ..., 0, 0, 0],
       [0, 1, 1, ..., 0, 0, 0],
       [0, 1, 1, ..., 0, 0, 0]], dtype=int64)

In [30]:
y.shape

(40479, 17)

In [32]:
y[:2]

array([[1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]], dtype=int64)

In [33]:
for i in range(0, 5):
    print(i)


0
1
2
3
4


In [34]:
merge = pd.DataFrame(y + y)

In [35]:
merge.head()

0   1   2   3   4   5   6   7   8   9   10  11  12  13  14  15  16
0   2   2   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
1   0   2   2   2   2   0   0   0   0   0   0   0   0   0   0   0   0
2   0   2   0   2   0   0   0   0   0   0   0   0   0   0   0   0   0
3   0   2   0   2   0   0   0   0   0   0   0   0   0   0   0   0   0
4   0   2   2   2   0   2   2   0   0   0   0   0   0   0   0   0   0

In [4]:
x = np.arange(0, 10, 1)

In [7]:
x[0:5]

array([0, 1, 2, 3, 4])

In [17]:
for id in range(0, (2340//1000)+1):
    print(id)

0
1
2


In [14]:
2340//1000

2